### ISSUE TITLE
Inicio automático en KDE 4

### ISSUE THREAD

**Issue by RGB-es** [javierllorente/qrae#1]
Con la versión 0.4.1 en KDE 4.11.5, qRAE ya no abre automáticamente en el inicio de sesión. He creado una entrada en **Preferencias del sistema → Arranque y apagado → Autoarranque** para iniciar qRAE con la sesión, pero el programa abre maximizado en lugar de «solo icono» como en las versiones anteriores (las versiones 0.3 recordaban el estado de la aplicación en el nuevo arranque).

**Comment by javierllorente** [comment]
¿Qué valor tiene la entrada "Visibility" de ~/.config/qRAE/Diccionario castellano de la RAE.conf?
A mí se me autoinicia qRAE 0.4.1 minimizado en icono bajo KDE 4.14.3. En "Arranque y Apagado → Gestión de sesiones" tengo marcada la opción "Restaurar sesión previa."

**Comment by RGB-es** [comment]
Tengo _Visibility=true_ y también está configurada la opción de restaurar sesión previa. 

EDITO: he probado a borrar el archivo de configuración y reiniciar el programa. El nuevo archivo se generó con _visibility=false_, lo cambié pro _true_, reinicié... y sigue igual, no inicia con la sesión.

**Comment by javierllorente** [comment]
Tiene que poner `Visibility=false` para que se inicie minimizado en la bandeja del sistema. Si lo cambias por `true`, hará lo contrario de lo que quieres hacer.

**Comment by RGB-es** [comment]
Ok, vuelta a visibility=false. Sigue sin iniciar con la sesión de KDE, pero cuando lo lanzo abre cerrado en la bandeja del sistema.

**Comment by javierllorente** [comment]
El inicio automático de la aplicación al iniciar sesión lo gestiona KDE.  Echa un vistazo a la opción de autoarranque en preferencias del sistema.
