### ISSUE TITLE
Autocompletado no parece funcionar en KDE 4

### ISSUE THREAD

**Issue by RGB-es** [javierllorente/qrae#2]
En el _ChangeLog_ para 0.4.1 se menciona:

_Nueva funcionalidad: consulta directa al hacer clic en el término del autocompletado_

No logro ver esta funcionalidad usando qRAE 0.4.1 en KDE 4.11.5 (paquete instalado desde el repositorio KDE:/Extra en openSUSE 13.1)

**Comment by javierllorente** [comment]
No me he explicado bien. Me refiero al autocompletado de términos previamente consultados. 
1. Tecleas parte del término previamente consultado
2. Haces clic en el autocompletado → te lleva directamente a la definición sin tener que hacer un clic adicional en buscar (o tener que dar a intro).

**Comment by RGB-es** [comment]
Así es como lo entendí ;) Cuando tecleo algo previamente buscado no ofrece opciones

**Comment by javierllorente** [comment]
Inicialo desde la consola, haz una consulta y copia y pega el resultado aquí.

**Comment by RGB-es** [comment]
Aquí va:

> qrae
> "Qt Warning - invalid keysym: dead_actute" 
> Leyendo ajustes... 
> db: "/home/usuario/.local/share/data/qraeqRAE/historial.sqlite" 
> QSqlDatabase: QSQLITE driver not loaded
> QSqlDatabase: available drivers: QMYSQL QMYSQL3
> Error. No se ha podido abrir la base de datos 
> QSqlQuery::exec: database not open
> progreso:  50 
> progreso:  100 
> (cargado) 
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> QSqlQuery::exec: database not open
> progreso:  10 
> QSqlQuery::exec: database not open
> db: insert 
> QSqlQuery::exec: database not open
> progreso:  21 
> progreso:  41 
> progreso:  50 
> progreso:  100 
> (cargado) 
> progreso:  10 
> progreso:  13 
> progreso:  17 
> progreso:  21 
> progreso:  27 
> progreso:  30 
> progreso:  33 
> progreso:  36 
> progreso:  100 
> (cargado)

**Comment by javierllorente** [comment]
Prueba a instalar el paquete `libQt5Sql5-sqlite` y haz la misma consulta dos veces. Fíjate si te aparece el autocompletado.

**Comment by RGB-es** [comment]
Pues parece que tengo que actualizar a openSUSE 13.2, porque libQt5Sql5-sqlite no está disponible para 13.1 (está en repositorios extras, como el KDE:Qt5, pero no en los oficiales). La falla es en la distro, por lo que podemos dar por cerrado el caso. ¡Muchas gracias por mantener qRAE!

**Comment by javierllorente** [comment]
No, no hace falta que actualices tu versión de openSUSE (y tampoco es un fallo de la distribución). En la 13.1 el nombre del paquete es otro (lo acabo de ver); `libqt5-sql-sqlite`. Si puedes, pruébalo y me cuentas. 
Gracias.

**Comment by RGB-es** [comment]
¡Probado! Funciona perfectamente. ¡Muchas gracias!

**Comment by javierllorente** [comment]
Estupendo. Me alegro de que funcione :-)
Acabo de mandar los cambios a KDE:Extra.
