### ISSUE TITLE
Diccionario panhispánico de dudas y diccionario de antónimos y sinónimos

### ISSUE THREAD

**Issue by icaroperseo** [javierllorente/qrae#4]
Buen día!

Antes que nada te felicito y agradezco la dedicación que le brindas a este magnifico proyecto. Por otra parte, me preguntaba si existe la posibilidad de añadir estos diccionarios a qRAE Desktop y Android.

Un cordial saludo!

**Comment by javierllorente** [comment]
Buenas tardes:
Sí que se podrían añadir pero ahora estoy centrado en sacar una nueva versión de qRAE (me falta muy poco) y también tengo pensado liberar el código de la aplicación de Android.
Saludos
