### ISSUE TITLE
manpage

### ISSUE THREAD

**Issue by icaroperseo** [javierllorente/qrae#5]
Buen día Javier!

Tengo la intención de empaquetar tu aplicación para que posteriormente sea propuesta su inclusión a los repositorios oficiales de Debian —de hecho ya dispongo del paquete formalmente—, pero desafortunadamente no puedo concluir con el procedimiento anteriormente descrito debido principalmente a que el software encargado de verificar que se cumplan los lineamientos de dicha distribución —Lintian— me requiere la inclusión de una _manpage_. Por lo anterior, me pregunto si existe la posibilidad de que pudieras proporcionar alguna base sobre la cual pudiera trabajar.

De antemano, agradezco tu atención.

Un cordial saludo!

**Comment by javierllorente** [comment]
Buenas tardes:

Lo siento, pero qdc no tiene página de manual ni tengo pensado incluirlo por ahora, ya que no usa parámetros. ¿Tiene sentido tener un manual en blanco? ;)
A lo mejor se puede ignorar que no tenga página de manual para que no te salga la advertencia correspondiente.

Saludos
